CREATE TABLE IF NOT EXISTS CUSTOMERS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FirstName VARCHAR(20) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  --addresss
  Street VARCHAR(50) NOT NULL,
  City VARCHAR(50) NOT NULL,
  Zip VARCHAR(20) NOT NULL,
  Country VARCHAR(50),
  --powerstuff
  AccessKey TEXT NOT NULL,
)